### ISSUE TITLE
intel_gpu_frequency missing a library?

### ISSUE THREAD

**Issue by CaptInsano** [ich777/intel-gpu-top#1]
unRAID 6.8.3
CPU: Intel(R) Core(TM) i9-9900 CPU @ 3.10GHz

Issue:

I can run "intel_gpu_top" no problem but when I try to run "intel_gpu_frequency" I get the following error.

```
root@Tower:~# intel_gpu_frequency
intel_gpu_frequency: error while loading shared libraries: libprocps.so.8: cannot open shared object file: No such file or directory

```

Any help would be greatly appreciated.

**Comment by ich777** [comment]
Yes that's actually because I mainly builded it for 6.9.0 and in 6.9.0 libprocps is included by default and I've also included intel_gpu_frequency afterwards (I'm thinking of removing it since it's not really needed).
If I include that in the package I can break actually other things on Unraid 6.9.0rc2

You can upgrade 6.9.0 rc2 or you install the libraries by hand, open up a Unraid terminal and enter these commands:
```
cd /tmp
wget http://slackware.cs.utah.edu/pub/slackware/slackware64-current/slackware64/a/procps-ng-3.3.16-x86_64-3.txz
installpkg procps-ng-3.3.16-x86_64-3.txz
rm -rf /tmp/procps-ng-3.3.16-x86_64-3.txz
```

But keep in mind that other dependencies can also be missing.

May I ask why you need intel_gpu_freqency (because I may remove it in an update version of the plugin)?

**Comment by CaptInsano** [comment]
To be honest, I was mainly using the plugin for gpu_top but was interested in seeing the output of gpu_frequency (curiosity, very non-critical!!).

I may have a go of manually installing the library in 6.8.3 but as you stated it will work in 6.9 anyway.

Thanks for your work!
