### ISSUE TITLE
[Question] What controls the version of intel driver used?

### ISSUE THREAD

**Issue by NickM-27** [ich777/intel-gpu-top#3]
This might be more of a question for unraid in general, but how does the version of the intel driver used get specified? If a newer version of the driver includes fixes is there any way as an unraid user to update this? Or are they part of unraid OS only and we have to wait for unraid to update the driver?

**Comment by ich777** [comment]
@NickM-27 my plugin is not a driver...
The plugin simply provides intel_gpu_top so that it can be utilized by the GPU-Statistics plugin or anything else.

However the driver itself comes from the Kernel, you have to wait for a new Unraid release to get the latest and greatest driver, so to speak the driver version is always tied to the Kernel version.
Unraid uses the `i915` and on newer version the `xe` driver in combination with the `i915` driver.

Hope that makes sense...

**Comment by NickM-27** [comment]
yes that does make sense and is what I figured, the intel_gpu_top just enables the driver if the go file hasn't been changed. Will close this as the question has been answered

> Unraid uses the i915 and on newer version the xe driver in combination with the i915 driver.

do you know if that is currently in Unraid 7 beta2? 

I just got an arc a750 and am trying to figure out a few things like how much power the card reports using, was reading about the xe driver potentially bridging the gap to provide more information about arc gpus

**Comment by ich777** [comment]
> do you know if that is currently in Unraid 7 beta2?

Yes.


> I just got an arc a750 and am trying to figure out a few things like how much power the card reports using, was reading about the xe driver potentially bridging the gap to provide more information about arc gpus

You can use `sensors` since this is a PCI device it reports everything there.
Sadly enough these cards are using a lot of power and are in my opinion not worth using it to transcode.
I also have to say that they are really fast at transcoding but the idle power draw is pretty insane to me (~30W minimum on my A580).
However AV1 is also not fully supported, at least encoding not and in my opinion (again :D ) it's a bit to early to jump on the AV1 train.

**Comment by NickM-27** [comment]
yeah, that is the unfortunate conclusion that I also seem to be arriving at
